### ISSUE TITLE
Error when trying to connect to a wrong port

### ISSUE THREAD

**Issue by MatteoBattilana** [Cylix/tacopie#11] opened 2017-05-08 21:39 UTC
I've tested the client code and I get this error if I use a wrong port number:

```
terminate called after throwing an instance of 'tacopie::tacopie_error'
  what():  connect() failure
```

**Comment by Cylix** [comment] 2017-05-09 02:38
Hi,

This is an expected behavior.
If your port is the wrong one, the TCP Client will attempt to connect but will fail because no service is available on the given host:port.
Thus, we throw a `tacopie::tacopie_error` exception.

If necessary, you can catch the exception in order to handle the case of an unsuccessful connection:

```cpp
try {
   client.connect(host, port);
}
catch (const tacopie::tacopie_error& e) {
   //! Do something in case of connection failure
   std::cerr << "Fail to connect to " << host << ":" << port << std::endl;
   std::cerr << e.what() << std::endl;
}
```

I close this issue but feel free to re-open it if you feel unclear or if you have any other questions.

Best!

**Closed by Cylix** 2017-05-09 02:38 UTC
